### ISSUE TITLE
Documentation & Demos

### ISSUE THREAD

**Issue by billywhizz** [just-js/just#10]
I'm going to create this issue and leave it open so i can post some updates on various documentation, demo and example work i have been doing and for any Q&A around that.

There seems to have been some interest in the project recently which I am encouraged by. I have questioned my sanity a few times on this little journey so it's nice to see that either i am not insane or at least there are some other equally insane folks who think doing this in JS is a good idea.

If anyone has any suggestions for demos, useful docs and examples please post them here. Also, if you have any suggestions for where best to discuss this that would suit everyone let me know. There are so many options these days it's hard to know the best forum. I set up a [gitter](https://gitter.im/just-js/community) community a while back which is one option. Maybe a google group would be best? It's a pity github does not have an integrated forum.

For now, I am finishing up some work on a [demos repo](https://github.com/just-js/demos/) which will hopefully be a good starting point for folks new to the platorm and the idea is to walk through various features of the platform, talk about the code and do a little benchmarking and comparison along the way. I'll have chapters 01-04 finished over next day or so.

For a few people who have been asking about a nice http api i have had some success with a [little experiment here](https://github.com/just-js/demos/tree/main/04-http-server). It has a similar api to express/fastify etc. and the performance numbers are looking very good and on a par with the hideous and unmaintainable code in the techempower repo which i stopped working on once i saw the numbers i liked.

@whyCPPgofast @hiqsociety @pranaypratyush @kizerkizer @vaaas @episage @rw3iss @ChrisGitIt @hc-codersatlas @antonkatz @IvanTurgenev @MarshalOfficial @amoorahmat. apologies for pinging you but you are the folks who have been involved in various discussions so far. if that is not cool let me know.

![fast](https://user-images.githubusercontent.com/159073/109219266-4aa15000-77af-11eb-8fd4-b0b4b898d1fe.png)

**Comment by antonkatz** [comment]
Hi @billywhizz I'm more than happy to see updates about the project!

**Comment by whyCPPgofast** [comment]
I can definitely relate with the insanity part... Good work on the http server example.

**Comment by MarshalOfficial** [comment]
Hi @billywhizz 
in the case of documentation, I had enjoyed FastAPI docs
https://fastapi.tiangolo.com/
I hope this might be helpful to check.

**Comment by iandrc** [comment]
@billywhizz your links don't work for some reason.

![image](https://user-images.githubusercontent.com/63982045/112643687-4c614080-8e4d-11eb-97a4-af4043210563.png)

We can fix them, I guess :)

**Comment by McSneaky** [comment]
> I have questioned my sanity a few times on this little journey so it's nice to see that either i am not insane or at least there are some other equally insane folks who think doing this in JS is a good idea.

@billywhizz I'm quite sure you are insane :smile: 

Having said that, I must add that it's coolest project I've seen in past year or so! Really waiting till I get some more free time to get my hands on it! :yum: :man_technologist:

**Comment by Skaytacium** [comment]
This is one of the best runtime projects I've seen in a long time, the TechEmpower benchmarks prove that too. I'd love to develop using this framework.

I might be able to contribute a little to the docs as I'm analyzing the source code right now, so if you ever need help, feel free to ask.

I really liked the [discord.js](https://discord.js.org/#/docs/main/stable/general/welcome) docs, anything like that would be nothing short of amazing.

**Comment by noahehall** [comment]
@billywhizz github does have `discussions` 

we're using it in the github copilot preview and its not too bad (imo)

**Comment by billywhizz** [comment]
yes. i set them up [here](https://github.com/just-js/just/discussions). should be good enough for now i think.

**Comment by paulocoghi** [comment]
As in AWS Copilot CLI repository, it's possible to _(optionally)_ choose to put Just docs on the same repo as Just, on the subfolder _docs_.

This is not required, but may be util on helping update the docs on the same PR where a new feature or any important change is being pulled, avoiding the bureaucracy to contributors in making two PRs (one for the code, another for the docs).

**Comment by MikeGrateful** [comment]
Why not support Windows

**Comment by billywhizz** [comment]
> Why not support Windows

i'm not completely against the idea, but i find keeping it to one or a small number of very similar platforms makes everything simpler, easier to understand for newbies etc. i also see increasing options for running everything inside containers in vscode and elsewhere. that should make it easy to build test and run in containers on any platform. these days, most folks seem to use linux for server deployments and that's where most of the server-side innovation seems to be happening, so right now, linux and linux on different architectures is a priority for me.

if you are interested in porting to windows, i am happy to help out in any way i can and can discuss options for how to make it work without massively complicating the codebase. i discovered this recently which would be useful: https://github.com/piscisaureus/wepoll.
