### ISSUE TITLE
Can't get modules to run

### ISSUE THREAD

**Issue by mattiasewers** [just-js/just#11]
Hi!

I'm on ubuntu and trying to get the example in VSCode.md to run but can't. Just following the instructions i still get `TypeError: Cannot read property 'fib' of undefined`. I'm I missing somthing?

Or the http server example with the following:
```
make runtime
sudo make install
make MODULE=http module
sudo make -C modules/http install
make examples
cd examples/http
just server.js
```

same there `TypeError: Cannot destructure property 'http' of 'just.library(...)' as it is undefined.`

**Comment by billywhizz** [comment]
hi @mattiasewers. i'll take a look. should be pushing out a new release over weekend and will make sure examples are working. i'll also be adding some automated tests and docs over coming weeks. thanks for your patience!

**Comment by mattiasewers** [comment]
No thank you for this library! No worries, I just sent to replace node with this so very excited.

**Comment by billywhizz** [comment]
> No thank you for this library! No worries, I just sent to replace node with this so very excited.

=) well, it's still very early stage. interested to know what you find attractive about the project and why you are looking to replace node.js with it? i am seeing a few other people expressing similar sentiments. i'm not sure i see it as a replacement/competitor for node.js, at least not in a general sense. but could be an alternative if you are looking for something that is easier to hack on and gives you lower level access than you would get with node.js.

**Comment by mattiasewers** [comment]
Yes I'm looking for something more easily hackable

**Comment by mattiasewers** [comment]
@billywhizz let me know if I can help with anything!

**Comment by billywhizz** [comment]
hi @mattiasewers thanks for the offer. i'll be keen to have some other involved going forward for sure. sorry again for delays - i am dealing with some personal issues here past couple of weeks. will hopefully have something useful with bugfixes/docs/http examples next week. i have been working on it but not had time to sit down and pull it altogether.

**Comment by mattiasewers** [comment]
No worries take your time.

**Comment by iandrc** [comment]
@mattiasewers @billywhizz 

It works on MacOS Big Sur just fine. I followed the instructions outlined in `VSCode.md`, and here's the result:

<img width="828" alt="Screenshot 2021-03-27 at 19 10 36" src="https://user-images.githubusercontent.com/63982045/112728526-6aec3800-8f30-11eb-84d2-406a132c5f54.png">

@mattiasewers did you set `JUST_HOME=$(pwd)/just`?

Though the `fib` example doesn't work as intended, afaik

**Comment by billywhizz** [comment]
yes. it worked for me when i tested on ubuntu 18.04 too. i couldn't reproduce this issue. @mattiasewers if you are still having the issues could you provide some more info (logs, etc.) on what you are seeing?

**Comment by mattiasewers** [comment]
@billywhizz works for me now, thanks!
