### ISSUE TITLE
thread support ?

### ISSUE THREAD

**Issue by mcarbonneaux** [just-js/just#16]
can you add thread support ? this while be killer feature....

**Comment by billywhizz** [comment]
you can spawn threads and do work in them but v8 does not allow access to a v8 isolate from multiple threads without doing some heavy duty locking. there are some examples here of running isolates in separate threads, sharing buffers between then doing atomic operations on those buffers. https://github.com/just-js/examples/blob/main/thread/atomics.js

**Comment by mcarbonneaux** [comment]
woow  !
