### ISSUE TITLE
http example doesn't seem to see the very first request on startup... 

### ISSUE THREAD

**Issue by rw3iss** [just-js/just#2]
Hi @billywhizz 
I've been messing with the http example to build a sort of runtime web/http server library around Just, but there's this thing happening where only the first request (since server startup) doesn't seem to make it to the onConnect handler... It's not such a huge issue since all subsequent requests seem to work fine, but it seems odd, and wanted to mention it:

In the http example we have:

```
    function onConnect(sock) {
        const self = this;
        stats.conn++;
        const stream = createHTTPStream(sock.buf, maxPipeline);
        const { buf, size } = responses[200];
    
        sock.onReadable = () => {
            const bytes = sock.pull(stream.offset);
    
            if (bytes <= 0) 
                return;
            
            let headers = stream.getHeaders().split('\n');
            let pathParts = headers[0].split(' ');
            print("Method: " + pathParts[0] + ", url: " + pathParts[1]);
    
            const err = stream.parse(bytes, count => {
                qps += count;
                stats.rps += bytes;
    
                if (sock.write(buf, count * size) <= 0) 
                    return;
    
                stats.wps += (count * size);
            })
    
            if (err < 0) print(`error: ${err}`)   // Todo: handle app error
        }
    
        sock.onWritable = () => {}
        sock.onEnd = () => stats.conn--;

        return this;
    }

    function start() {
        print("Starting server...");
        createServer(onConnect).listen();
        return this;
    }
```

You can see I added a print() statement in onConnect. 
When I hit any url (ie. http://localhost:3000/test).. two requests are sent from the browser. One is for the favicon, and the other for the url endpoints (/test). The onConnect print statement only sees the favicon request, but not /test. Only when I try a second request (and subsequent) will it show that /test is being reached.

I'm not entirely sure why, maybe it's to do with the socket initialization on first run, or the way createServer is initialized... but it's only happening on the very first request.

If you might have any ideas, let me know, but I'll dig in a little.

**Comment by billywhizz** [comment]
hi @rw3iss. yes, the examples are in a serious state of disrepair. apologies for that. i need to spend some time cleaning them up and providing some docs for them.

let me see if i can pull together a simple working example based on the latest code. should have something for you soon.

**Comment by rw3iss** [comment]
> hi @rw3iss. yes, the examples are in a serious state of disrepair. apologies for that. i need to spend some time cleaning them up and providing some docs for them.
> 
> let me see if i can pull together a simple working example based on the latest code. should have something for you soon.

Cool, yeah I see that, no worry :-)... I was able to work with the http example.

Actually I think this issue might have been related to my code. After cleaning up a bit and moving the location of where I was calling my request handlers (was calling before stream.parse... but still within sock.onReadable, but for some reason this worked, presumably because the onReadable is only called once the buffer has content, which will always have the request headers first anyway... but still don't know why it wouldn't hit the handler the first time in that case as it should have always been called before stream.parse anyway... however, it's working now after moving that inside stream.parse (I'm not terribly versed in working with streams and the net level stuff so much, but nice practice). I'll close for now, but let you know if I notice anything strange otherwise.

I uploaded the code I've been building the last few days... 
https://github.com/rw3iss/just-web
Trying to build a basic web application library on top of Just... seems to work decently so far for basic request handling, routing, string/json response helpers, very basic middleware system... still need to look into POST/body parsing... but wanted to get this up working. Can see readme if interested... am using nodemon and esbuild to develop locally, so I added a section to update the Dockerfile with node (lol), nodemon, and esbuild... but don't need to use those if one doesn't want to.

Cheers!

**Comment by billywhizz** [comment]
@rw3iss that's cool ryan! i will check it out. i have got a basic example working here: https://github.com/just-js/examples/tree/main/http. this used the http module which is using picohttpparser. i'll see if i can add some more to this and flesh it out a bit. feel free to hack on it and submit a PR if you have any suggested changes.

**Comment by rw3iss** [comment]
@billywhizz Sweet! Nice example, thank you. I cleared out the old existing http example code I was using, and integrated your new http example code into the just-web library sample I'm working on (see above repo for modifications). 

I think I'll follow along with your http implementation and integrate or contribute what I can. Mostly I think it'd be nice to have help with the basic stream parsing, and then I'm pretty comfortable with organizing and writing other library features on top of the underlying net/http/stream parsing stuff... Maybe we can try to keep the very basic low-level http server/parsing/socket stuff as part of that core... and then abstract on top of that, which I assume is the goal... but anyway, I've updated my example repo using your code... mostly just within src/lib/application.js if interested. 

One thing I noticed which might make sense to help keep the underlying core http code lean (I'm sure you have plans to clean it up, but just communicating)... is how the socket object is populated with the response helpers (ie. sock.json, sock.html, etc...) within the example's server.js server.onConnect(sock) listener. I presume this method is called everytime a new request comes in... which is initializing and attaching all those helpers on the object on every request... but one would assume it'd be more efficient to not do any of that during socket read/onConnect for every single request... and instead move them to a static external or helper library, but let me know if there's a downside to that or if I have it wrong, if you want :-)

**Comment by rw3iss** [comment]
@billywhizz I didn't read through or try your bundle/build code, but I'm wondering... is it not possible to use an existing bundler for things built with this project? I'm looking at esbuild here (webpack and the like are way too bloated, obviously), but esbuild is pretty sweet and slim (and supports typescript, plugins, etc, and is super fast/written in Go). I'm using it for the just-web library... just wondering if there's a reason something like that shouldn't be used here?

Also

**Comment by billywhizz** [comment]
@rw3iss maybe bundling is the wrong term. i am working on something which will let us compile a whole application and all it's dependencies (c++ modules and js libraries) into a single executable or shared library for easy distribution. i don't think esbuild does that. am also not really interested in minification as that then requires sourcemaps, adding more complexity and indirection. i am also not interested in typescript other than having definitions to help with intellisense/docs. these are all things that folks could take advantage of in userland but i don't see them being used in the core. i want core to be small, simple, js-only, self-contained and easy to understand without having to learn lots of tooling.

**Comment by rw3iss** [comment]
@billywhizz Cool, that makes sense... I think I understand that and your concerns... So one could theoretically use the builder/bundler to first compile their entire Just library/application, and then that could be further imported into client-facing applications using other build tools ("userland").

**Comment by billywhizz** [comment]
not sure i quite understand the workflow you are suggesting. at moment i am looking at ability to take an "application" which is a combination of c++ modules and javascript code and compile it all into either
- a single purpose executable which you can distribute/deploy on it's own and runs your application without all the other command line options the normal just binary has
- a dll/shared library which you can run as an application using the standard just runtime (the dll is obviously much smaller as it doesn't have all of the runtime embedded in it.

you can see the experiment [here](https://github.com/just-js/examples/blob/main/bundle/bundle.js). it's working pretty well.

i haven't really thought much about bundling like webpack or esbuild do - minification, source-map generation etc. i see them very much as front end technologies where minification is more important as you have to repeatedly transfer the entire app over the internet before clients can run it. for server side, these things don't matter so much imho. i'm also not sure where typescript fits into the picture. at moment am very much focused on using the platform for building lower level system-y software on the server and not much else. i don't see it ever becoming a general purpose all singing all dancing platform like node.js. it is very much aiming for a much smaller market that is not particularly well served by node.js in it's current incarnation.

**Comment by rw3iss** [comment]
Nod, I understand your workflow I think...
I'm not interested in frontend applications with Just... strictly backend/Node replacement/web stuff.
Minification is only a requirement on the backend as far as dead-code removal, and faster parsing... sourcemaps not required.
What I was implying was that... I think... theoretically your builder could be used to package an entire backend application (C++ and Just modules) into something, and then... theoretically, another simpler more abstract application could be written in strictly Just/Javascript, utilizing the built application... but obviously they could be bundled together at build time... just depends on the approach, if you or someone wants to build and expose a lower-level application to build upon, for example.

**Comment by billywhizz** [comment]
hmm. yes, it should be possible to do something like this. i've been doing some experiments with bundling up an entire directory of code as a module which could then be imported by another application as a library/module. am still in the weeds with it at the moment and just testing ideas out.

i'm currently in middle of a refactor branch that let's you decide what you want from core in your application before compilation. it's working pretty good. for example i can just write a config like this and then run a command to bundle up only the c++ modules and JS libs i need:

```javascript
const libs = [
  'lib/fs.js',
  'lib/loop.js',
  'lib/path.js',
  'lib/process.js'
]

const version = '0.0.5'

const capabilities = [] // list of allowed internal modules, api calls etc. TBD

const modules = [{
  name: 'sys',
  obj: [
    'modules/sys/sys.o'
  ]
}, {
  name: 'fs',
  obj: [
    'modules/fs/fs.o'
  ]
}, {
  name: 'net',
  obj: [
    'modules/net/net.o'
  ]
}, {
  name: 'vm',
  obj: [
    'modules/vm/vm.o'
  ]
}, {
  name: 'epoll',
  obj: [
    'modules/epoll/epoll.o'
  ]
}]

const target = 'just'
const main = 'just.js'

module.exports = { version, libs, modules, capabilities, target, main }
```

**Comment by billywhizz** [comment]
i'd also like way to only enable api calls that are required by the app. this would be useful for building more secure applications with limited surface area and limited syscall interaction.

**Comment by rw3iss** [comment]
Ah that's cool! I'm wondering what the use cases are for a smaller bundle/built package (besides the mentioned security concerns)... ie. maybe it'd be to ship Just as a runtime on embedded devices, or send it to the browser to be run in WASM eventually, or something like that... I don't know what else would benefit so much from a smaller package...
