### ISSUE TITLE
Install script is looking for the wrong folder

### ISSUE THREAD

**Issue by Feijo** [just-js/just#25]
When I run this command (from the README):
`sh -c "$(curl -sSL https://raw.githubusercontent.com/just-js/just/0.1.1/install.sh)"`

It returns this error after:
```
sh: 4: cd: can't cd to just-0.1.1
sh: 5: make: not found
```

The folder the script created is called `just-0.1.0`

**Comment by billywhizz** [comment]
ooh wow. that is pretty old. i will check it out. thx.
