### ISSUE TITLE
Are PRs welcome?

### ISSUE THREAD

**Issue by Feijo** [just-js/just#27]
I'd be keen to start contributing to this project, but apparently no PRs have been approved/merged so far. Just wondering if PRs are welcome at all? 

Can you post a roadmap or create tasks so people can contribute to this project?

Thanks

**Comment by billywhizz** [comment]
hi. yes. but i would prefer it folks could wait for next release which should be out in next few days. it should involve a big clean up of the code and added documentation/tests. once i have that out would be happy to start planning a roadmap and taking contributions and would be delighted to have some other folks involved!

**Comment by Feijo** [comment]
Sweet, thanks for clarifying.
