### ISSUE TITLE
Rocksdb > terark

### ISSUE THREAD

**Issue by jeremy-coleman** [just-js/just#28]
Seems good? Idk. 
https://github.com/bytedance/terarkdb
Looks like they just forked rocks and made it faster. Only mentioning bc i was looking at recent commits and rocks was among them. Bytedance is tiktok btw

**Comment by billywhizz** [comment]
this looks cool - thanks for the pointer. should be pretty easy to put a module for just-js together for it based on the existing rocksdb one.
