### ISSUE TITLE
new releases, no changes.

### ISSUE THREAD

**Issue by tomByrer** [just-js/just#31]
I think your GitHub bot drank too much caffeine; no changes from v01.2 to v0.1.3, but it was released as a new version anyway.

**Comment by billywhizz** [comment]
yes. in the absence of a well thought out release strategy and any ability to have versioned libraries and modules i am keeping the release versions in sync across all repos. so everytime i make a significant change to just/libs/modules i will bump version on them all to be the same. this makes the build process easier for now as all we need to do is get modules and libs for same current version of just.

**Comment by tomByrer** [comment]
I see.  Thanks for explaining!
