### ISSUE TITLE
is it safe to stick just_home & just_target in startup file (e.g. bashrc) ?

### ISSUE THREAD

**Issue by noahehall** [just-js/just#35]
in `just/readme.md`
```sh
export JUST_HOME=$(pwd)/just
export JUST_TARGET=$JUST_HOME
```

is it recommended to just stick these in a startup file?

**Comment by mkvalor** [comment]
That should cause no harm.  However -- you would want to specify an explicit path for the first one, which points to the specific subdir where you installed just. Otherwise, it would would expect a dir named just/ to exist at the top level of your home directory.

**Comment by billywhizz** [comment]
yes. you can put them in a startup file. i would be careful when building though as that code is not very robust and could be bugs that would lead to you overwriting and/or deleting things you don't want to. i haven't seen one yet though. but, if you want to be extra safe, you could use docker to do any building.

are you guys using this? i don't have much time to work on it at moment, but interested to hear people's thoughts. i have another little experiment [here](https://github.com/billywhizz/spindle) that is actually nicer in a lot of ways and faster than just-js in most of the baseline benchmarks.
