### ISSUE TITLE
just.library('http') return undefined (windows10 wsl2 ubuntu)

### ISSUE THREAD

**Issue by Everton-Sales** [just-js/just#45]
const { http } = just.library('http')
just.print("hello")
just.print(just.memoryUsage().rss)
just.print(http)

Terminal:

hello
10129408
undefined

**Comment by billywhizz** [comment]
i need to bring docs up to date. to start from the beginning this should work:

```
wget https://github.com/just-js/just/archive/refs/tags/current.tar.gz
tar -zxvf current.tar.gz
cd just-current/
# this will download the modules into current directory
make modules
# build the just runtime
make runtime
# install the runtime to /usr/local/bin/just
sudo make install
# build the http module
MODULE=http make module
# install the http module to /usr/local/lib/just
sudo make -C modules/http install
```

and repeat the last two steps for any other modules you want to use. it used to throw an error when a shared library wasn't found but don't currently. i might change that.

let me know if this works for you. if not, we should be able to figure it out. would be interested to know if it all works on wsl2.

**Comment by Everton-Sales** [comment]
it worked perfectly, thank you

**Comment by billywhizz** [comment]
> it worked perfectly, thank you

great! glad it is working as expected on wsl2. there is a bash [script](https://github.com/just-js/modules/blob/main/build.sh) to build all the modules also. you might want to leave out rocksdb if you don't plan on using it as it takes *ages* to build.

**Comment by Everton-Sales** [comment]
hi,
in modules/build.sh very errors:
-----------------------------------------------
In file included from blake3.cc:1: blake3.h:4:10: fatal error: just.h: No such file or directory     4 | #include "just.h"
-----------------------------------------------
if I change to: "../../just.h" 
-----------------------------------------------
then:
-----------------------------------------------
../../just.h:4:10: fatal error: v8.h: No such file or directory     4 | #include <v8.h> 
-----------------------------------------------
and so on...
 
I didn't get it with docker either 
 
sorry about my English. 
 
Everton
Em Ter 01/03/22 00:10, Andrew Johnston ***@***.*** escreveu:

 

it worked perfectly, thank you

great! glad it is working as expected on wsl2. there is a bash script to build all the modules also. you might want to leave out rocksdb if you don't plan on using it as it takes ages to build.

**Comment by billywhizz** [comment]
@Everton-Sales ah yes, missing documentation again... i have lots of work to do!

if you look [here](https://github.com/just-js/modules/blob/main/blake3/Makefile#L18) you can see the modules expect and environment variable set for JUST_HOME. this should point to the "just-current" directory i referred to above (where you downloaded, extracted and built the just runtime). so if that directory is /home/everton/just-current then run this

```
export JUST_HOME=/home/everton/just-current
cd /home/everton/just-current/modules
./build.sh
```

**Comment by Everton-Sales** [comment]
hi,
ok, including  export PATH=$PATH:JUST_HOME :-)

Errors:
-----------------------------
In file included from ffi.cc:1:
ffi_just.h:5:10: fatal error: ffi.h: No such file or directory
    5 | #include <ffi.h>
-----------------------------
In file included from ../../src/include/postgres.h:47,
                 from chklocale.c:17:
../../src/include/utils/elog.h:71:10: fatal error: utils/errcodes.h: No such file or directory
   71 | #include "utils/errcodes.h"
-----------------------------
+ 2 warnings:
-----------------------------
ip.cc:145:24: warning: variable ‘buf’ set but not used [-Wunused-but-set-variable]
  145 |     Local<ArrayBuffer> buf = args[3].As<ArrayBuffer>();
-----------------------------
signing.cc:220:7: warning: variable ‘r’ set but not used [-Wunused-but-set-variable]
  220 |   int r = X509_REQ_set_version(x509_req, 0);
-----------------------------

**Comment by billywhizz** [comment]
yup. ffi is broken because you need to install libffi

```
apt install -y libffi-dev
```

and postgres library, for some reason i haven't had time to figure out yet, always fails when built from the makefile. this library is pretty incomplete and there is a different, pure-JS postgres client [library](https://github.com/just-js/libs/tree/main/pg) that works better, but if you want to fix this and get it working, this *should* do the trick:

```
cd modules/pg
cd deps/postgresql-12.3/
make -C src/bin
make -C src/include
make -C src/interfaces/
cd ../..
make clean library 
sudo make install
```

**Comment by Everton-Sales** [comment]
hi,
ok, including  export PATH=$PATH:JUST_HOME :-)

Errors:
-----------------------------
In file included from ffi.cc:1:
ffi_just.h:5:10: fatal error: ffi.h: No such file or directory
    5 | #include <ffi.h>
-----------------------------
In file included from ../../src/include/postgres.h:47,
                 from chklocale.c:17:
../../src/include/utils/elog.h:71:10: fatal error: utils/errcodes.h: No such file or directory
   71 | #include "utils/errcodes.h"
-----------------------------
+ 2 warnings:
-----------------------------
ip.cc:145:24: warning: variable ‘buf’ set but not used [-Wunused-but-set-variable]
  145 |     Local<ArrayBuffer> buf = args[3].As<ArrayBuffer>();
-----------------------------
signing.cc:220:7: warning: variable ‘r’ set but not used [-Wunused-but-set-variable]
  220 |   int r = X509_REQ_set_version(x509_req, 0);
-----------------------------

**Comment by Everton-Sales** [comment]
hi, in WSL I found a problem with $PATH, other than echo $PATH and the ./build.sh inside "modules" didn't work. I managed to solve it by copying the ./build.sh to the folder above (just or just-current) and modifying it like this: 

#!/bin/bash
MODULES=${2:-"blake3 encode epoll ffi fs html http inspector io ip jkvm memory net openssl  profiler seccomp sha1 signal sqlite sys tcc thread udp vm zlib"}
for m in $MODULES
do
	MODULE=$m make module
	make -C modules/$m install
done

**Comment by Everton-Sales** [comment]
you should inform in the README.md, in "Build and Run" the g++ dependency: 

sudo apt instal g++
