### ISSUE TITLE
Lets Merge runtime-js and its kernel directly into this project

### ISSUE THREAD

**Issue by frank-dspeed** [just-js/just#49]
At Present this projects offers single binary builds to executeable

how ever we could merge the abondoned runtime-js project which is a minimal c++ kernel to boot v8 this gives us just-js as unikernel

so we can directly deploy it without needing a additional OS 

it is not much code and it is inside the philosophie of this project to be educational 

https://github.com/runtimejs-comm/runtime

**Comment by billywhizz** [comment]
hi @frank-dspeed. this will be a completely different project then with completely different goals and layer upon layer of added complexity, which is exactly what i want to avoid. i'm all for someone like yourself having a look at doing this as a separate project that builds on top of just-js and happy to help/advise with the effort but i don't ever see it become part of the core.

i have done some experiments with building a full "unikernel" VM in javascript with just-js - using firecracker or lkvm. this is possible with just-js out of the box as a separate project and i think would be a better direction to go in. i'll see if i can clean up these experiments and write them up on the blog in coming weeks. if what you want is a bundled OS/runtime/application in a single binary that launches a linux kernel on kvm then take a look at these.

https://github.com/billywhizz/just-apps/tree/main/busybee
https://github.com/billywhizz/just-apps/tree/main/kvm
https://github.com/billywhizz/just-apps/tree/main/virt
