### ISSUE TITLE
Mariadb Support

### ISSUE THREAD

**Issue by rkanagaraj** [just-js/just#51]
Hai,
Can you help me out, how can use with Mariadb.....

**Comment by billywhizz** [comment]
hi @rkanagaraj. there is no mysql/mariadb driver implemented currently so someone would have to write a wrapper around an existing C library. currently, there are only limited and partially implemented drivers for SQLite, Postgres, Rocksdb, DuckDB which you can find [here](https://github.com/just-js/modules).

**Comment by rkanagaraj** [comment]
Thank you for reply...keep rock....

**Comment by rkanagaraj** [comment]
Right now I am using php swoole for my production, I have developed own framework for application backend to talk with mariadb where front end is nuxtjs... I wanna develop my next one with just js for flutter front end.

**Comment by ramezrafla** [comment]
@billywhizz 

There is a nice example of mariadb c connector in action [here](https://github.com/hholzgra/connector-c-examples). Now they don't cache the connection like you do in pg.cc. How hard do you think it will be to migrate this to Just? Some direction would be appreciated (which module to use as base etc.)
