### ISSUE TITLE
avoid clock_gettime syscall by use vDSO

### ISSUE THREAD

**Issue by pavelmash** [just-js/just#59]
While analyzing just TechEmpower app I discover many `clock_gettime` syscalls.
We in `mormot` have the same problem some times ago, and solves it by linking with libc to use vDSO (Linux subsytem what expose some of kernel level functions to user space)  - see https://github.com/synopse/mORMot/pull/281/files 

Hope it helps you to improve (already amazing) TechEmpower results

**Comment by billywhizz** [comment]
thanks. i think those calls are coming from v8. VDSO should be in use for all those calls. call overhead from JS is only ~12 nanoseconds with a v8 fastcall.
