### ISSUE TITLE
[Question] ESM Support?

### ISSUE THREAD

**Issue by ayushmanchhabra** [just-js/just#60]
> commonjs modules, no support for ES modules

What's the reason for not supporting ES modules? Have you tried to in the past?

> avoid abstraction as much as possible

Would ESM count as an abstraction?

**Comment by kungfooman** [comment]
Seems to be mostly ideologically driven, not rooted in any specific technical limitation, just like the lack of semicolons and lack of JSDoc documentation...

**Comment by billywhizz** [comment]
there is ESM support - just pass the `--esm` flag. i have not had time to look at just-js in the past long while due to personal circumstances. @kungfooman if you feel like contributing some JSDoc please do. :wink:

**Comment by ayushmanchhabra** [comment]
Thanks for the info!

**Comment by kungfooman** [comment]
> there is ESM support - just pass the `--esm` flag. i have not had time to look at just-js in the past long while due to personal circumstances. @kungfooman if you feel like contributing some JSDoc please do. 😉

There is a chance that I will :sweat_smile: You talked about a new kind-of-like-just-but-better version, wouldn't it be wasted effort?

A group needs coordination, Discord etc. would be nice

**Comment by billywhizz** [comment]
yeah. but ime discord can be an enormous time drain and is incredibly frenetic. defo good for hype tho. i'll see if i can set one up and start a discussion at least. 

i have a lot of thoughts about a JS runtime that is more focused on lower level apis and more tailored for server-side development (i.e. not using all the Web APIs which have been very much tailored for front-end and security needs of the browser). all the JS runtimes now seem to be focused on adding more and more tooling and "DX", mostly for front-end devs. also concerning that two of the three main JS runtimes are now backed by VC and very much motivated by locking people into their ecosystem. I do think Deno's approach of embracing the Web API's over all else can be successful though - they have an emerging and well backed set of standards behind them. But I also think there is a "gap in the market" for a JS runtime that doesn't force you to use a bunch of APIs that feel very clunky for backend development and hide what is happening "under the hood" behind endless layers of abstraction.

i remember when node.js [came out first](https://github.com/nodejs/node/tree/v0.0.1/src) and the thing that really struck me was the simplicity and how easy it now was to get at the lower level api's from JS and make fast software without having to get too much into the complexities of C++. early on i did argue, ineffectively, that node.js should be kept to a very small core and tooling/frameworks could be built on top of that by node.js themselves or the wider community. but it's hard to argue with the success of the approach they took. i just wish it was easy to use the core runtime without all the extra baggage and write JS "close to the metal".

maybe this is just the way the industry is going, but i'm not so sure it's good in the longer term. will hopefully be able to write these ideas up in more detail, release the new code and start a discussion before making any calls about future directions. keen to hear any thoughts others may have. :pray:

**Comment by billywhizz** [comment]
FYI, i also have a nicer implementation of ESM modules in my other runtime i am hacking on. It exposes all the loading and caching of modules to JS land, which makes it easier for non C/C++/Rust folks to hack on and experiment with. One of key goals I would have for any new JS runtime would be that there is a low level set of primitives exposed to JS land where it's easy then to iterate on and for a larger group of people to contribute. 

One of the things I find most frustrating with Node.js, Deno and now Bun is the codebases are absolutely enormous and full of very complex C++/Zig/Rust which places a high barrier to entry on anyone that wants to work at a lower level or do things differently to how the maintainers have decided.

**Comment by kungfooman** [comment]
> One of the things I find most frustrating with Node.js, Deno and now Bun is the codebases are absolutely enormous and full of very complex C++/Zig/Rust which places a high barrier to entry on anyone that wants to work at a lower level or do things differently to how the maintainers have decided.

Yep, same sentiment, I also don't like how JS projects adopt TS. Typing is good obviously, but why running a cumbersome build step after every little change... just use JSDoc with the same TS language server.

To make it ESM specific: a simple low-level API to change module path resolution for a custom importmap implementation would be nice. Right now it's so stuck and requires package.json fields etc. and just feels completely awkward - Browser API `<script type="importmap">` feels easier-to-use/hackable than anything in Node.js.

**Comment by TimiBolu** [comment]
> yeah. but ime discord can be an enormous time drain and is incredibly frenetic. defo good for hype tho. i'll see if i can set one up and start a discussion at least.
> 
> i have a lot of thoughts about a JS runtime that is more focused on lower level apis and more tailored for server-side development (i.e. not using all the Web APIs which have been very much tailored for front-end and security needs of the browser). all the JS runtimes now seem to be focused on adding more and more tooling and "DX", mostly for front-end devs. also concerning that two of the three main JS runtimes are now backed by VC and very much motivated by locking people into their ecosystem. I do think Deno's approach of embracing the Web API's over all else can be successful though - they have an emerging and well backed set of standards behind them. But I also think there is a "gap in the market" for a JS runtime that doesn't force you to use a bunch of APIs that feel very clunky for backend development and hide what is happening "under the hood" behind endless layers of abstraction.
> 
> i remember when node.js [came out first](https://github.com/nodejs/node/tree/v0.0.1/src) and the thing that really struck me was the simplicity and how easy it now was to get at the lower level api's from JS and make fast software without having to get too much into the complexities of C++. early on i did argue, ineffectively, that node.js should be kept to a very small core and tooling/frameworks could be built on top of that by node.js themselves or the wider community. but it's hard to argue with the success of the approach they took. i just wish it was easy to use the core runtime without all the extra baggage and write JS "close to the metal".
> 
> maybe this is just the way the industry is going, but i'm not so sure it's good in the longer term. will hopefully be able to write these ideas up in more detail, release the new code and start a discussion before making any calls about future directions. keen to hear any thoughts others may have. 🙏

I really like the approach of just js. Any thoughts on windows and macos interop yet? Is it possible for your new runtime (spindle) to be brought into just?

**Comment by billywhizz** [comment]
> Yep, same sentiment, I also don't like how JS projects adopt TS. Typing is good obviously, but why running a cumbersome build step after every little change... just use JSDoc with the same TS language server.

Yeah. I am not a big fan of TS and I think JSDoc does most of what is needed. I like the dynamic nature of JS and the fact there is no build step, especially for quick iteration, exploration etc. Introducing a build step has always seemed odd to me, but I can understand why there has been a push for it coming from orgs managing large JS projects.

> To make it ESM specific: a simple low-level API to change module path resolution for a custom importmap implementation would be nice. Right now it's so stuck and requires package.json fields etc. and just feels completely awkward - Browser API `<script type="importmap">` feels easier-to-use/hackable than anything in Node.js.

at moment, the module loading is completely exposed to JS-land so should be easy for embedders to implement module resolution whatever way they want to. i should be able to push the latest code for the "new" runtime up later today, but this is what it basically looks like from JS side right now.

```JavaScript
async function onModuleLoad (specifier, resource) {
  if (!specifier) return
  if (moduleCache.has(specifier)) {
    const mod = moduleCache.get(specifier)
    if (!mod.evaluated) {
      //console.log(`main.evaluateModule.1 ${mod.identity} ${specifier} ${resource}`)
      mod.namespace = await spin.evaluateModule(mod.identity)
      mod.evaluated = true
    }
    return mod.namespace
  }
  const src = loadSource(specifier)
  const mod = spin.loadModule(src, specifier)
  mod.resource = resource
  moduleCache.set(specifier, mod)
  const { requests } = mod
  for (const request of requests) {
    const src = loadSource(request)
    const mod = spin.loadModule(src, request)
    moduleCache.set(request, mod)
  }
  if (!mod.evaluated) {
    //console.log(`main.evaluateModule.2 ${mod.identity} ${specifier} ${resource}`)
    mod.namespace = await spin.evaluateModule(mod.identity)
    mod.evaluated = true
  }
  return mod.namespace
}

function onModuleInstantiate (specifier) {
  if (moduleCache.has(specifier)) {
    return moduleCache.get(specifier).identity
  }
  const src = loadSource(specifier)
  const mod = spin.loadModule(src, specifier)
  moduleCache.set(specifier, mod)
  return mod.identity
}
spin.setModuleCallbacks(onModuleLoad, onModuleInstantiate)
```

**Comment by billywhizz** [comment]
@TimiBolu 
> I really like the approach of just js. Any thoughts on windows and macos interop yet? Is it possible for your new runtime (spindle) to be brought into just?

yeah. i really want to keep things simple, so windows support is problematic but i don't think it would be much work in the new runtime ("spin" currently but not sure about naming yet) to support the following:

- Linux on x86_64/aarch64
- BSD on x86_64/aarch64
- macos on x86_64/aarch64
- Android

windows support would be possible of course as v8 runs there, but how to do cross-platform in general is up for discussion right now. the core is very little code and almost all the standard library is auto-generated C/C++ directly against system API's. so, most of the cross-platform work could be surfaced to JS-land, which i think would be nice.

There is another whole option i am currently exploring to just use [deno_core](https://github.com/denoland/deno_core), which already runs cross platform and exposes a lot of very nice low-level stuff. it's Rust though, so am not sure that would be "in the spirit" of what I am trying to do here - i love the idea of combining the simplicity of both JS and C together. At same time, it may be the most pragmatic option given the support it already has. Deno has lots of nice features and is incredibly well designed. I did some work with the folks there last year and it was a real education! :sweat_smile:

**Comment by Bessonov** [comment]
> there is ESM support - just pass the `--esm` flag. i have not had time to look at just-js in the past long while due to personal circumstances. @kungfooman if you feel like contributing some JSDoc please do. 😉

Not tested yet, but it sounds great! Then this one could be removed?

https://github.com/just-js/just/blob/d2675a15f1715d31f0ce8340967e3faa97fc7055/README.md?plain=1#L83
