### ISSUE TITLE
EvalError: Code generation from strings disallowed for this context

### ISSUE THREAD

**Issue by motherfogger** [just-js/just#61]
Should this be a valid JS code? I got an error: 

EvalError: Code generation from strings disallowed for this context
    at new Function (<anonymous>)
    at objectConverter

// whole source code from [d3/d3-dsv](https://github.com/d3/d3-dsv/blob/main/src/dsv.js),  i was trying to port the lib
// part of code: 
    while ((t = token()) !== EOF) {
      var row = [];
      while (t !== EOL && t !== EOF) row.push(t), t = token();
      if (f && (row = f(row, n++)) == null) continue;  // error here
      rows.push(row);
    }

**Comment by billywhizz** [comment]
it's [disabled](https://github.com/just-js/just/blob/main/main.h#L68) by default, but you can override with the **--no-disallow-code-generation-from-strings** v8 command line flag, e.g.

```
just --no-disallow-code-generation-from-strings eval 'just.print((new Function("return 1"))())'
```
