### ISSUE TITLE
Is there any way to add nodejs library ? 

### ISSUE THREAD

**Issue by Mupli** [just-js/just#66]

**Comment by billywhizz** [comment]
this project isn't active anymore @Mupli. the thing i am working on currently is [here](https://github.com/just-js/lo).

not aiming for node.js compat for this low level library but plan on implementing as many of the WinterCG/Node.js api's on top of this at some point, if there is any interest.

**Comment by Mupli** [comment]
too bad this project was 4th in the world if is about performance. 
https://www.techempower.com/benchmarks/#hw=ph&test=composite&section=data-r22

What was missing was the compatibility with the vast spectrum of js libraries that could be installed via npm. 

I was looking into lo and it is too low level for me.
If there could be some wrapper that could make things easier and allow to use npm libs.

**Comment by McSneaky** [comment]
You can use NPM packages, just not packages that rely on some Node specific stuff

**Comment by Mupli** [comment]
how you mean that i would need to: 
1. install just to system.
2. npm init 
3.. modify package.json  with  start: just app.js

Btw. why just is not in npm repository ?

**Comment by billywhizz** [comment]
hi @Mupli 

the just-js/just project is not actively maintained anymore. just-js/lo is the current thing i am working on and, at some point, i may "resurrect" just-js/just as a more "batteries included" and "standard JS" compliant runtime built on top of lo.

https://github.com/just-js/lo

if lo looks interesting, feel free to raise an issue on that repo and we can discuss. lo module resolution is not compatible with node/npm right now but, as an embedder, you can override module resolution and roll your own however you want. this would allow building something npm or jsr compatible on top of lo.

there's an example that should be working with latest lo [here](https://github.com/just-js/docs/blob/main/example/loader/loader.js). if you run

```shell
$ lo loader.js lib/asm/asm.js

LO_CACHE=1 lo loader.js lib/asm/asm.js
lib/asm/asm.js
fetching https://raw.githubusercontent.com/just-js/lo/0.0.15-pre/lib/asm/asm.js for lib/asm/asm.js from loader.js
1135
lib/asm/assembler.js
fetching https://raw.githubusercontent.com/just-js/lo/0.0.15-pre/lib/asm/assembler.js for lib/asm/assembler.js from loader.js
13327
lib/asm/compiler.js
fetching https://raw.githubusercontent.com/just-js/lo/0.0.15-pre/lib/asm/compiler.js for lib/asm/compiler.js from loader.js
1590
Assembler,Compiler,Registers
```

this will load the module over http from github and any modules it depends on. right now http (using libcurl) is synchronous/blocking but there will be a native async-compatible implementation of fetch ready soon. :pray:
