### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by whyCPPgofast** [just-js/just#9]
First of all dude... You are fucking awesome! When I saw the the techempower benches I couldn't stop giggling 😁. Its so bizarre seeing JS up there.

I know your hands are full right now and theres no docs yet...

Anyway here is what I would like to see in the future:
- websocket client,
- base64 hmac hashes example (not sure if cryptography is implemented yet)

I've seen people asking for npm support but I believe that isn't the way to go. Just my 2 cents.

**Comment by billywhizz** [comment]
hi @whyCPPgofast. thanks - am glad you got a giggle. i think it's cool to see JS up there slugging it out with the heavyweights. amazing the amount of abuse the language gets when it is really so capable and so widely used.

there is a websocket parser implemented in core [here](https://github.com/just-js/just/blob/main/lib/websocket.js). it is used for the inspector protocol for debugging but can just as easily be used for websocket server or client. you can see it being used in the inspector [here](https://github.com/just-js/just/blob/main/lib/inspector.js#L105). the code is a little ugly but i can look at wrapping it up a bit more and adding some needed functionality.

also, there is an encoding/decoding module [here](https://github.com/just-js/modules/blob/main/encode/encode.cc). the code should be there for base64 and hex encode/decode but i have only exposed the encode methods as that was all i needed at the time.

i'll be putting out a new demo of a http server with a nicer api shortly. i also fixed a major issue in the debugger so debugging with chrom/vscode works like a dream now. keep an eye on the blog/twitter. 

docs will be coming too. a little delayed so likely the weekend or next week before i get anything useful out.

**Comment by billywhizz** [comment]
there is also basic crypto and tls modules based on openssl [here](https://github.com/just-js/modules/tree/main/openssl). i have code working for mbedtls also but would need to dig it out. there are some examples which may be working [here](https://github.com/just-js/examples/tree/main/openssl).

**Comment by MarshalOfficial** [comment]
Annotation role base Authorization, Authentication:
for example in net core web API when you want to secure a specific method of the controller for an admin role, it is pretty awsome like below:

[Authorize(Role="admin")]
Public ActionResult SomeMethod(int headerparam, [FromBody] BodyObjectParam){
{

**Comment by billywhizz** [comment]
> Annotation role base Authorization, Authentication:
> for example in net core web API when you want to secure a specific method of the controller for an admin role, it is pretty awsome like below:
> 
> [Authorize(Role="admin")]
> Public ActionResult MethodName(int headerparam, [FromBody] BodyObjectParam){
> return Ok(something);
> {

hi @MarshalOfficial. this is a nice feature but for JS this would require some language support which would be more a task for the ES standards folks i think. just is based on v8 so whatever gets implemented there will be in just.

i also don't see functionality like this being in core. this would be nice as a separate userland project. one of the things i think node.js has suffered from is supporting too many high level abstractions in core. e.g. http. http should not be a core platform feature. someone else will always do a better implementation and you end up with a library taking up space in core that nobody wants to use. 

with just, i want it to be a very small and simple and fast and secure layer on top of the system interface. folks then have a substrate they can depend on and that doesn't have huge code churn and they can build whatever nice abstractions they want, including things like streams and http servers/clients, on top of it.
